FROM python:3.10-slim

WORKDIR /app

# Copy mms-consumer code
COPY mms-consumer/ .

# Copy model-builder code
COPY model-builder/ ./model-builder

# Install dependencies
RUN pip install redis numpy

CMD ["python", "scheduler.py"]
