FROM confluentinc/cp-kafka:7.5.0

# Switch to root to modify permissions
USER root

WORKDIR /app
COPY create-topics.sh /app/create-topics.sh
RUN chmod +x /app/create-topics.sh

# Switch back to default Kafka user
USER appuser

ENTRYPOINT ["/app/create-topics.sh"]
